version: '3.8'

services:
  bootstrap:
    image: store/marklogicdb/marklogic-server:${mlVersionTag}
    hostname: "${mlBootstrap}"
    container_name: "${mlBootstrap}"
    dns_search: ""
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME_FILE=mldb_admin_username
      - MARKLOGIC_ADMIN_PASSWORD_FILE=mldb_admin_password
      - TZ=Europe/Prague
    volumes:
      - ./data/MarkLogic1:/var/opt/MarkLogic
    secrets:
      - mldb_admin_password
      - mldb_admin_username
    ports:
      - 7100-7110:8000-8010
      - 7197:7997
    networks:
    - external_net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    extra_hosts:
      host.docker.internal: host-gateway

  node1:
    image: store/marklogicdb/marklogic-server:${mlVersionTag}
    hostname: "${mlNode1}"
    container_name: "${mlNode1}"
    dns_search: ""
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME_FILE=mldb_admin_username
      - MARKLOGIC_ADMIN_PASSWORD_FILE=mldb_admin_password
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=Europe/Prague
    volumes:
      - ./data/MarkLogic2:/var/opt/MarkLogic
    secrets:
      - mldb_admin_password
      - mldb_admin_username
    ports:
      - 7200-7210:8000-8010
      - 7297:7997
    depends_on:
    - bootstrap
    networks:
    - external_net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    extra_hosts:
      host.docker.internal: host-gateway

  voter:
    image: store/marklogicdb/marklogic-server:${mlVersionTag}
    hostname: "${mlVoter}"
    container_name: "${mlVoter}"
    dns_search: ""
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME_FILE=mldb_admin_username
      - MARKLOGIC_ADMIN_PASSWORD_FILE=mldb_admin_password
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=Europe/Prague
    volumes:
      - ./data/MarkLogic3:/var/opt/MarkLogic
    secrets:
      - mldb_admin_password
      - mldb_admin_username
    ports:
      - 7300-7310:8000-8010
      - 7397:7997
    depends_on:
    - bootstrap
    networks:
    - external_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 6G
    extra_hosts:
      host.docker.internal: host-gateway

  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    #restart: always
    hostname: "haproxy"
    container_name: "haproxy"
    volumes:
      - ./haproxy-2.4:/usr/local/etc/haproxy/
    ports:
      - "8000-8010:8000-8010"
      - "8404:8404"
    expose:
      - "8000-8010"
    networks:
      - external_net
    depends_on:
    - voter
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

secrets:
  mldb_admin_password:
    file: ./mldb_admin_password.txt
  mldb_admin_username:
    file: ./mldb_admin_username.txt

networks:
  external_net:
    driver: bridge
